# Dimas Ramadhani
# 4611422126
# Rusnanda Farhan

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
file_path = "/content/drive/MyDrive/Celerates Python/Tugas Python 2/train.csv"

In [3]:
df = pd.read_csv(file_path)
print(df.shape)
df.head()

(1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [5]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [6]:
# Check for missing values in the dataset
missing_values = df.isnull().sum()

In [7]:
# Filter only columns with missing values
missing_values[missing_values > 0]

LotFrontage      259
Alley           1369
MasVnrType       872
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64



---

# mengatasi Missing value pada kolom tersebut dengan teknik yang sudah pernah dipelajari:
# 1. Mengisi missing value : dengan teknik-tenik mengisi missing value
# 2. Menghapus missing value : hapus baris atau kolom



---

# LotFrontage

median adalah pilihan yang kuat untuk mengisi nilai yang hilang dalam kolom numerik seperti LotFrontage karena ketahanannya terhadap outliers, kemampuannya untuk merepresentasikan distribusi data yang tidak normal, dan relevansinya sebagai ukuran pemusatan untuk data numerik.

In [8]:
# Mengisi nilai yang hilang di kolom LotFrontage dengan median
df['LotFrontage'].fillna(df['LotFrontage'].median(), inplace=True)

<ipython-input-8-b7b8b031a372>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['LotFrontage'].fillna(df['LotFrontage'].median(), inplace=True)

In [9]:
# Mengecek apakah masih ada missing values
df['LotFrontage'].isnull().sum()

0



---

# Alley

menggunakan modus untuk mengisi nilai yang hilang di kolom Alley disebabkan karena relevansinya dengan data kategorikal, kemampuannya untuk meminimalkan bias dalam analisis, dan kesederhanaan dalam perhitungan. Modus memberikan representasi yang akurat dan efektif dari data yang ada, membantu menjaga integritas dataset saat menangani missing values.

In [10]:
# Mengisi nilai yang hilang di kolom Alley dengan modus
df['Alley'].fillna(df['Alley'].mode()[0], inplace=True)

<ipython-input-10-c5648afe8a8d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Alley'].fillna(df['Alley'].mode()[0], inplace=True)

In [11]:
# Mengecek apakah masih ada missing values
df['Alley'].isnull().sum()

0



---

# MasVnrType

menggunakan "None" untuk mengisi nilai yang hilang di kolom MasVnrType disebabkan karena memberikan indikasi jelas tentang ketidakadaan nilai, relevansinya dengan data kategorikal, dan kemampuannya untuk menghindari bias. Ini memastikan bahwa informasi yang ada dalam dataset tetap akurat dan dapat diinterpretasikan dengan baik saat melakukan analisis.

In [12]:
# Mengisi nilai yang hilang di kolom MasVnrType dengan "None"
df['MasVnrType'].fillna("None", inplace=True)

<ipython-input-12-ce78514d908d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['MasVnrType'].fillna("None", inplace=True)

In [13]:
# Mengecek apakah masih ada missing values
df['MasVnrType'].isnull().sum()

0



---

# MasVnrArea

menggunakan mean untuk mengisi nilai yang hilang di kolom MasVnrArea disebabkan karena relevansinya dengan data numerik, kemudahan implementasi, dan kemampuannya untuk meningkatkan kualitas data. Mean memberikan estimasi yang baik tentang nilai yang hilang dengan mempertimbangkan distribusi keseluruhan dari dataset.

In [14]:
# Mengisi nilai yang hilang di kolom MasVnrArea dengan mean
df['MasVnrArea'].fillna(df['MasVnrArea'].mean(), inplace=True)

<ipython-input-14-cc2336eba7bc>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['MasVnrArea'].fillna(df['MasVnrArea'].mean(), inplace=True)

In [15]:
# Mengecek apakah masih ada missing values
df['MasVnrArea'].isnull().sum()

0



---

# BsmtQual

menggunakan modus untuk mengisi nilai yang hilang di kolom BsmtQual disebabkan karena kemampuannya untuk merepresentasikan kategori yang paling umum, relevansinya untuk data kategorikal, dan potensi untuk menghindari bias dalam analisis. Metode ini memastikan bahwa informasi dalam dataset tetap akurat dan representatif saat menangani missing values.

In [16]:
# Mengisi nilai yang hilang di kolom BsmtQual dengan modus
df['BsmtQual'].fillna(df['BsmtQual'].mode()[0], inplace=True)

<ipython-input-16-6cbdb2570996>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BsmtQual'].fillna(df['BsmtQual'].mode()[0], inplace=True)

In [17]:
# Mengecek apakah masih ada missing values
df['BsmtQual'].isnull().sum()

0



---

# BsmtCond

menggunakan modus untuk mengisi nilai yang hilang di kolom BsmtCond disebabkan karena relevansinya dengan data kategorikal, kemampuannya untuk meminimalkan bias dalam analisis, dan kesederhanaan dalam perhitungan. Modus memberikan representasi yang akurat dari data yang ada, membantu menjaga integritas dataset saat menangani missing values.

In [18]:
# Mengisi nilai yang hilang di kolom BsmtCond dengan modus
df['BsmtCond'].fillna(df['BsmtCond'].mode()[0], inplace=True)

<ipython-input-18-a6cfeac15cde>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BsmtCond'].fillna(df['BsmtCond'].mode()[0], inplace=True)

In [19]:
# Mengecek apakah masih ada missing values
df['BsmtCond'].isnull().sum()

0



---

# BsmtExposure

menggunakan "None" untuk mengisi nilai yang hilang di kolom BsmtExposure adalah pendekatan yang baik karena memberikan indikasi yang jelas tentang ketidakadaan data, relevansinya untuk kolom kategorikal, dan kemampuannya untuk menghindari bias. Dengan cara ini, informasi dalam dataset tetap akurat dan dapat diinterpretasikan dengan baik saat dilakukan analisis lebih lanjut.

In [20]:
# Mengisi nilai yang hilang di kolom BsmtExposure dengan "None"
df['BsmtExposure'].fillna("None", inplace=True)

<ipython-input-20-33c1e565a703>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BsmtExposure'].fillna("None", inplace=True)

In [21]:
# Mengecek apakah masih ada missing values
df['BsmtExposure'].isnull().sum()

0



---

# BsmtFinType1

menggunakan modus untuk mengisi nilai yang hilang di kolom BsmtFinType1 disebabkan karena ia mencerminkan kategori yang paling umum, relevansinya untuk data kategorikal, dan kemampuannya untuk meminimalkan bias. Pendekatan ini juga meningkatkan kualitas data dan mempersiapkan dataset untuk analisis yang lebih mendalam dan akurat.

In [22]:
# Mengisi nilai yang hilang di kolom BsmtFinType1 dengan modus
df['BsmtFinType1'].fillna(df['BsmtFinType1'].mode()[0], inplace=True)

<ipython-input-22-cd2cf98eca93>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BsmtFinType1'].fillna(df['BsmtFinType1'].mode()[0], inplace=True)

In [23]:
# Mengecek apakah masih ada missing values
df['BsmtFinType1'].isnull().sum()

0



---

# BsmtFinType2

Menghapus baris pada kolom BsmtFinType2 yang memiliki missing values adalah langkah penting untuk menjaga kualitas dan konsistensi data, mempermudah analisis, serta meningkatkan kinerja model.

In [24]:
#Menghapus baris yang mengandung missing values di kolom GarageCond
df.dropna(subset=['BsmtFinType2'], inplace=True)

In [25]:
# Mengecek ukuran dataset setelah penghapusan
df.shape

(1422, 81)



---

# Electrical

menggunakan modus untuk mengisi nilai yang hilang di kolom Electrical disebabkan karena relevansinya dengan data kategorikal, kemampuannya untuk meminimalkan bias dalam analisis, dan kesederhanaannya dalam perhitungan. Modus mencerminkan nilai yang paling sering muncul, menjaga integritas data dan memberikan gambaran yang lebih akurat tentang keadaan sistem kelistrikan dalam dataset.

In [26]:
# Mengisi nilai yang hilang di kolom Electrical dengan modus
df['Electrical'].fillna(df['Electrical'].mode()[0], inplace=True)

<ipython-input-26-c3170b94781d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Electrical'].fillna(df['Electrical'].mode()[0], inplace=True)

In [27]:
# Mengecek apakah masih ada missing values
df['Electrical'].isnull().sum()

0



---

# FireplaceQu

menggunakan modus untuk mengisi nilai yang hilang di kolom FireplaceQu disebabkan karena relevansinya dengan data kategorikal, kemampuannya untuk meminimalkan bias dalam analisis, dan kesederhanaan dalam perhitungan. Modus memberikan representasi yang akurat dan efektif dari data yang ada, membantu menjaga integritas dataset saat menangani missing values.

In [28]:
# Mengisi nilai yang hilang di kolom FireplaceQu dengan modus
df['FireplaceQu'].fillna(df['FireplaceQu'].mode()[0], inplace=True)

<ipython-input-28-f6beae11088f>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FireplaceQu'].fillna(df['FireplaceQu'].mode()[0], inplace=True)

In [29]:
# Mengecek apakah masih ada missing values
df['FireplaceQu'].isnull().sum()

0



---

# GarageType

menggunakan modus untuk mengisi nilai yang hilang di kolom GarageType disebabkan karena relevansinya dengan data kategorikal, kemampuannya untuk meminimalkan bias dalam analisis, dan kesederhanaannya dalam perhitungan. Modus memberikan representasi yang akurat dan efektif dari data yang ada, membantu menjaga integritas dataset saat menangani missing values.

In [30]:
# Mengisi nilai yang hilang di kolom GarageType dengan modus
df['GarageType'].fillna(df['GarageType'].mode()[0], inplace=True)

<ipython-input-30-d3c5dcbd60f0>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GarageType'].fillna(df['GarageType'].mode()[0], inplace=True)

In [31]:
# Mengecek apakah masih ada missing values
df['GarageType'].isnull().sum()

0



---

# GarageYrBlt

menggunakan median untuk mengisi nilai yang hilang di kolom GarageYrBlt disebabkan karena ketahanannya terhadap outliers, kemampuannya untuk merepresentasikan distribusi data yang tidak normal, dan relevansinya sebagai ukuran pemusatan untuk data numerik. Median memberikan estimasi yang stabil dan akurat untuk nilai yang hilang, menjaga integritas dataset dan meningkatkan kualitas analisis.

In [32]:
# Mengisi nilai yang hilang di kolom GarageYrBlt dengan median
df['GarageYrBlt'].fillna(df['GarageYrBlt'].median(), inplace=True)

<ipython-input-32-76e4b9c610c9>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GarageYrBlt'].fillna(df['GarageYrBlt'].median(), inplace=True)

In [33]:
# Mengecek apakah masih ada missing values
df['GarageYrBlt'].isnull().sum()

0



---

# GarageFinish

menggunakan modus untuk mengisi nilai yang hilang di kolom GarageFinish disebabkan karena relevansinya dengan data kategorikal, kemampuannya untuk meminimalkan bias dalam analisis, serta kesederhanaan dan efisiensinya dalam imputasi. Modus memberikan representasi yang akurat dan efektif dari data yang ada, membantu menjaga integritas dataset saat menangani missing values.

In [34]:
# Mengisi nilai yang hilang di kolom GarageFinish dengan modus
df['GarageFinish'].fillna(df['GarageFinish'].mode()[0], inplace=True)

<ipython-input-34-68b5d6e42011>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GarageFinish'].fillna(df['GarageFinish'].mode()[0], inplace=True)

In [35]:
# Mengecek apakah masih ada missing values
df['GarageFinish'].isnull().sum()

0



---

# GarageQual

menggunakan modus untuk mengisi nilai yang hilang di kolom GarageQual disebabkan karena relevansinya dengan data kategorikal, kemampuannya untuk meminimalkan bias dalam analisis, dan kemudahan dalam perhitungan. Modus memberikan representasi yang akurat dan efektif dari data yang ada, membantu menjaga integritas dataset saat menangani missing values.

In [36]:
# Mengisi nilai yang hilang di kolom GarageQual dengan modus
df['GarageQual'].fillna(df['GarageQual'].mode()[0], inplace=True)

<ipython-input-36-e5440add5893>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GarageQual'].fillna(df['GarageQual'].mode()[0], inplace=True)

In [37]:
# Mengecek apakah masih ada missing values
df['GarageQual'].isnull().sum()

0



---

# GarageCond

menggunakan modus untuk mengisi nilai yang hilang di kolom GarageCond disebabkan karena relevansinya dengan data kategorikal, kemampuannya untuk meminimalkan bias dalam analisis, dan kesederhanaannya dalam perhitungan. Modus memberikan representasi yang akurat dan efektif dari data yang ada, membantu menjaga integritas dataset saat menangani missing values.

In [38]:
# Mengisi nilai yang hilang di kolom GarageCond dengan modus
df['GarageCond'].fillna(df['GarageCond'].mode()[0], inplace=True)

<ipython-input-38-3cc8f7d0948a>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GarageCond'].fillna(df['GarageCond'].mode()[0], inplace=True)

In [39]:
# Mengecek apakah masih ada missing values
df['GarageCond'].isnull().sum()

0



---

# PoolQC

Menggunakan "None" untuk mengisi nilai yang hilang di kolom PoolQC disebabkan karena memberikan indikasi yang jelas tentang ketidakadaan nilai, relevansinya dalam konteks data kategorikal, dan kemampuannya untuk menghindari bias dalam analisis. Ini memastikan bahwa informasi dalam dataset tetap akurat dan dapat diinterpretasikan dengan baik, yang sangat penting untuk analisis data dan pemodelan yang lebih baik.

In [40]:
# Mengisi nilai yang hilang di kolom PoolQC dengan "None"
df['PoolQC'].fillna("None", inplace=True)

<ipython-input-40-f954f7e54e15>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['PoolQC'].fillna("None", inplace=True)

In [41]:
# Mengecek apakah masih ada missing values
df['PoolQC'].isnull().sum()

0



---

# Fence

menggunakan "None" untuk mengisi nilai yang hilang di kolom Fence disebabkan karena memberikan indikasi jelas tentang ketidakadaan pagar, relevansinya dengan data kategorikal, dan kemampuannya untuk menghindari distorsi informasi. Ini memastikan bahwa dataset tetap akurat dan informatif, memungkinkan analisis yang lebih baik dan keputusan yang lebih tepat berdasarkan data.

In [42]:
# Mengisi nilai yang hilang di kolom Fence dengan "None"
df['Fence'].fillna("None", inplace=True)

<ipython-input-42-f07b90ca233f>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fence'].fillna("None", inplace=True)

In [43]:
# Mengecek apakah masih ada missing values
df['Fence'].isnull().sum()

0



---

# MiscFeature

menggunakan "None" untuk mengisi nilai yang hilang di kolom MiscFeature disebabkan karena memberikan indikasi jelas tentang ketidakadaan fitur tambahan, relevansinya untuk data kategorikal, dan kemampuannya untuk menghindari bias. Ini memastikan bahwa informasi dalam dataset tetap akurat, sehingga memungkinkan analisis yang lebih baik dan pemodelan yang lebih tepat.

In [44]:
# Mengisi nilai yang hilang di kolom MiscFeature dengan "None"
df['MiscFeature'].fillna("None", inplace=True)

<ipython-input-44-efd1bdfecad1>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['MiscFeature'].fillna("None", inplace=True)

In [45]:
# Mengecek apakah masih ada missing values
df['MiscFeature'].isnull().sum()

0



---

In [46]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64